apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-consumer
  template:
    metadata:
      labels:
        app: nats-consumer
    spec:
      containers:
        - name: consumer
          image: ghcr.io/cuistops/nats-simple-demo/consumer:latest
          env:
            - name: NATS_URL
              value: "nats://nats.nats.svc.cluster.local:4222"

